services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: koye
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/koye
      REDIS_URL: redis://redis:6379
    ports: ["3000:3000"]
    depends_on: [postgres, redis]
